### ISSUE TITLE
Panic if GString contains null byte

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gtk-rs-core#10]
```rust
glib::GString::from("test\0");
```

> thread 'main' panicked at 'CString::new failed: NulError(4, [116, 101, 115, 116, 0])'

Not surprising, but can we do something about it? I was thinking about dropping null bytes in the `from()` function. But maybe I'm just to obsessed with having code that cannot panic :laughing:

**Comment by JAicewizard** [comment]
Could it be an option to implement `ToGlibPtr` for `CString` so that the users of glib have more control over the panic without doing double work??

Then all functions that use this trait could also have a version that takes a `CString` which would allow all usesr to handle the errors gracefully. Or instead of taking a CString directly, make the functions generic over `ToGlibPtr`.
