### ISSUE TITLE
Regression from 0.16 to 0.17: Panic in spawn_local doesn't work in tests

### ISSUE THREAD

**Issue by AaronErhardt** [gtk-rs/gtk-rs-core#1014]
Relm4 has two test cases that use panicking to figure out whether an object was destructed or not. This worked fine until I attempted to upgrade Relm4 to the latest gtk-rs release.

The error message is somewhat amusing:

```
running 1 test
test drop_after_quit - should panic ... FAILED

failures:

---- drop_after_quit stdout ----
thread 'drop_after_quit' panicked at 'App dropped', relm4/tests/drop_after_quit.rs:8:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
note: test did not panic as expected

failures:
    drop_after_quit
```

Basically, Rust tells me it panicked and it didn't panic at the same time. Since the test worked with the previous gtk-rs release, I assume this is a regression introduced by work on the futures code of gtk-rs-code with version 0.17, but I could be wrong.

The code of the example can be found here: https://github.com/Relm4/Relm4/blob/main/relm4/tests/drop_after_quit.rs

**Comment by sdroege** [comment]
Can you provide a standalone testcase for this that doesn't involve relm?

My guess is that this comes from https://github.com/gtk-rs/gtk-rs-core/pull/818 . Previously we were just ignoring any panics, which then propagated through the FFI layer and were maybe possible to catch from outside `g_main_loop_run()`. This however was UB and more often than not resulted in the process aborting or even segfaults, and in later Rust versions will consistently result in the process aborting.

You now have to catch panics by await on the `JoinHandle` that is returned by `spawn_local()`, and otherwise the panic is simply caught and ignored. Just like with tokio. That would fit with your observation that the panic was printed but the test itself did not notice the panic.

**Comment by AaronErhardt** [comment]
This is a minimal test case:

```rust
#[test]
fn spawn_local() {
    gtk::init().unwrap();
    let _application = gtk::gio::Application::new(None, gtk::gio::ApplicationFlags::FLAGS_NONE);

    gtk::glib::MainContext::ref_thread_default().spawn_local(async {
        panic!();
    });

    gtk::glib::MainContext::ref_thread_default().iteration(true);
}
```

Relm4 does something very similar btw: [runtime code](https://github.com/Relm4/Relm4/blob/main/relm4/src/component/sync/builder.rs#L210-L281)

The new behavior is better for sure. It's just very odd that Rust contradicts itself due to the new behavior.

I've [adjusted our test cases](https://github.com/Relm4/Relm4/commit/68dad6780633785f3c167bf4a5517665c722a8f4) now for the new behavior, so I think we can close this issue.

**Comment by sdroege** [comment]
> The new behavior is better for sure. It's just very odd that Rust contradicts itself due to the new behavior.

It's the same behaviour you get with `std::thread::spawn()` or `tokio::spawn()` FWIW. So it's at least more consistent now.
