### ISSUE TITLE
pango: missing is_paragraph_start and resolved_dir fields on LayoutLine

### ISSUE THREAD

**Issue by cmyr** [gtk-rs/gtk-rs-core#12]
These are both C bitfields, which do not have a stable representation in rust; accessing them will involve doing something fancy.

This came out of the discussion in gtk-rs/gtk3-rs#376.

**Comment by bilelmoussaoui** [comment]
The issue was fixed upstream and the getters are part of the not released yet v1.50 (we already have bindings for them though); this can be closed now.  See https://gtk-rs.org/gtk-rs-core/git/docs/pango/struct.LayoutLine.html#method.resolved_direction & https://gtk-rs.org/gtk-rs-core/git/docs/pango/struct.LayoutLine.html#method.is_paragraph_start
