### ISSUE TITLE
[FEATURE REQUEST] OutputStreamExtManual::write_all_future to not borrow buffer as 'static

### ISSUE THREAD

**Issue by felinira** [gtk-rs/gtk-rs-core#1263]
In theory [`OutputStreamExtManual::write_all_future`](https://gtk-rs.org/gtk-rs-core/stable/latest/docs/gio/prelude/trait.OutputStreamExtManual.html#method.writev_all_future) only needs to borrow `buffer` for the lifetime of its future. See [`futures-io::AsyncWriteExt::write_all`](https://docs.rs/futures/latest/futures/io/trait.AsyncWriteExt.html#method.write_all) for a similar method with less restrictive lifetime bounds.

Apart from that the method signature could use some improvement. The `Ok` variant contains an `Option<error>` which is rather confusing :sweat_smile:

**Comment by sdroege** [comment]
The problem here is cancellation. It needs to borrow the buffer for the lifetime of the futures *plus* until cancellation actually has taken place. That's why it is taking ownership of the buffer and passes it back to the caller.

This needs more features in Rust so that dropping the future can be guaranteed to wait until cancellation has happened.

**Comment by sdroege** [comment]
> Maybe using rust native async I/O methods are the better tradeoff then

They're implementing this via sync API and a threadpool, FWIW. For the same reason why `gio::FileOutputStream` does not implement `gio::PollableOutputStream`.

On Linux with iouring it would be possible to have actual async file IO.

What's your use-case here btw and why is the taking ownership of the input buffer so much of a problem? Keep in mind that IIRC tokio/async-fs are also internally copying the data to another buffer, for basically the same reasons.
