### ISSUE TITLE
[BUG] ObjectBuilder property population gets slower after application startup

### ISSUE THREAD

**Issue by exi** [gtk-rs/gtk-rs-core#1366]
**Bug description**

I have these three variants used to construct 1 million GObject subclass instances each:

```rust
    pub fn new_builder(id: u64, name: String) -> Self {
        let obj: AccountObject = Object::builder()
            .property("id", id)
            .property("name", name)
            .build();
        obj
    }

    pub fn new_setter(id: u64, name: String) -> Self {
        let obj: AccountObject = Object::builder()
            .build();
        obj.set_name(name);
        obj.set_id(id);
        obj
    }

    pub fn new_imp(id: u64, name: String) -> Self {
        let obj: AccountObject = Object::builder()
            .build();
        {
            let mut data = obj.imp().data.borrow_mut();
            data.id = id;
            data.name = name;
        }
        obj
    }

```

One uses ObjectBuilder to set properties, one uses property-setters and one just modifies the data directly.
The results of the creation:
```
Creation with new_builder() took 16385ms
Creation with new_setter() took 10925ms
Creation with new_imp() took 3867ms
```

According to my profiler, most of the time in the new_builder variant is spent in:
```
Object::new_internal() -> ObjectClassExt::list_properties
```

This makes a noticable different when constructing large ListModels for big tables.

# EDIT
Reproduction repository here: https://github.com/exi/gtk-rs-obj-builder

The slowness of the ObjectBuilder variant only appears after the application is started up.

**Comment by bilelmoussaoui** [comment]
That is actually very known. The problem is the various checks that are made by new_internal and we would need some (unsafe?) variant that doesn't go through them. 

That would be useful for builder patterns that are generated by gir and possibly in the future for a builder pattern generated by the Properties macro

**Comment by exi** [comment]
Are there any downsides to directly inject properties into the imp()?
I'd guess we would miss some property-notify-event signals, but those would not be fired in the ObjectBuilder as well.
Or are there some other hazards I should be aware of?

**Comment by sdroege** [comment]
Can you provide the full, runnable code for this? The numbers for the second variant are confusing and I'd like to know what's going on there.

**Comment by exi** [comment]
@bilelmoussaoui @sdroege I boiled it down to a reproducible change, which was quite surprising:

https://github.com/exi/gtk-rs-obj-builder

ObjectBuilder gets significantly slower after the application is started up.
The code in the repo results in output like this:

```rust
Before startup
Setter took 9223ms
Builder took 9134ms
After startup
Setter took 9626ms
Builder took 12054ms
```

**Comment by sdroege** [comment]
Untangled this a bit. When running it separately (each of the 4 cases is a separate process) to avoid caching effects (e.g. the way you create the list will keep the allocation for the next check after the `clear()`):

```
After startup
Setter took 5666ms
After startup
Builder took 7374ms
Before startup
Setter took 5690ms
Before startup
Builder took 5667ms
```

So the main question here is indeed why the builder takes longer after startup. The others all seem approximately the same.

**Comment by sdroege** [comment]
`g_object_class_list_properties()` -> `g_param_spec_pool_list()` needs about 10x as many instructions after startup, that seems to be the main culprit here.

```cpp
  g_hash_table_foreach (pool->hash_table,
                        G_TYPE_IS_INTERFACE (owner_type) ?
                          pool_depth_list_for_interface :
                          pool_depth_list,
                        &data);
```

This hash table contains all pspecs of all types. So after startup it contains quite many pspecs. That's obviously not very efficient.

The setter variant goes through `g_object_class_find_property()` -> `g_param_spec_pool_lookup()`. And that just does one or more (once for each parent class) normal hash table lookups with the type and property name. That's obviously faster if there are a lot of types registered.

Considering that implementation inside GObject, our approach to use `list_properties()` was clever but unfortunately defeated the purpose because it's super slow compared to just looking up each property individually.

Preparing a PR for here...

**Comment by sdroege** [comment]
After my PR:

```
After startup
Setter took 5519ms
After startup
Builder took 5469ms
Before startup
Setter took 5536ms
Before startup
Builder took 5597ms
```

Now they're all about the same, so object construction is about 30% faster now.
