### ISSUE TITLE
Should `SignalHandlerId` be `Copy` or should `disconnect` accept `&SignalHandlerId`

### ISSUE THREAD

**Issue by mahkoh** [gtk-rs/gtk-rs-core#269]
`SignalHandlerId` is not `Copy` and `disconnect` consumes it. This is done so that the same `SignalHandlerId` is not accidentally used to disconnect distinct signal handlers in case that `SignalHandlerId` overflows.

First of all, this can only happen on 32 bit systems or Windows because it's a 64 bit integer otherwise.

Secondly, this makes it impossible to store an object and `SignalHandlerId`s in a struct and, e.g., disconnect the signal handlers on drop because you cannot move the `SignalHandlerId`. One workaround is to store the `SignalHandlerId`s in a `Vec` or behind `Option`.

Thirdly, the `SignalHandlerId`s overflowing is considered a bug in glib. https://github.com/GNOME/glib/blob/861afbe63953c2442658444bc147a7ea15213b8a/gobject/gsignal.c#L688-L689

Fourthly, if `SignalHandlerId` overflows, then gtk-rs-core aborts: https://github.com/gtk-rs/gtk-rs-core/blob/346cc681052d24c387ee2755902129c7bf26c937/glib/src/signal.rs#L60

Therefore the current setup makes working with signals harder only to prevent certain high-level errors that I am not convinced occur at a significant rate if ever.

It would not be a breaking change to make `SignalHandlerId` `Copy`.

**Comment by GuillaumeGomez** [comment]
I am completely lost: we do want to implement `Copy` on `SignalHandlerId` because we want to prevent people to disconnect a signal twice, same reason why `disconnect` is taking ownership of it. I don't see how it's related to overflow...

As for putting `SignalHandlerId` in a struct, I definitely don't see the issue. if you want to disconnect the signal outside of a `drop` implementation, then yes, you need to use `Option`, it's just how rust works.

**Comment by mahkoh** [comment]
> we want to prevent people to disconnect a signal twice

Why? If a signal has already been disconnected then disconnecting it again is a no-op except that glib will emit a warning message.

>I don't see how it's related to overflow...

That seemed like the only reasonable explanation for the current behavior to me. If overflow comes into play, then disconnecting multiple times can cause logic errors. If overflow is not in the picture, then disconnecting twice causes no harm whatsoever.

>if you want to disconnect the signal outside of a drop implementation

How would you do it inside a drop implementation?

**Comment by sdroege** [comment]
> Fourthly, if `SignalHandlerId` overflows, then gtk-rs-core aborts:

Well, no. Because if it overflows then GTK already killed the process via `g_error()` in the code you linked:

> Thirdly, the `SignalHandlerId`s overflowing is considered a bug in glib. https://github.com/GNOME/glib/blob/861afbe63953c2442658444bc147a7ea15213b8a/gobject/gsignal.c#L688-L689

I don't think overflow is something you have to worry about here. If it happens then it will fail hard and immediately.

----

That `SignalHandlerId` is not `Copy` and disconnecting takes ownership of it is intentional. While it does not prevent all possible bugs (you can still disconnect twice if you try hard enough, you can disconnect on the wrong object, ...), it at least avoids disconnecting twice and pushes people to properly handle the signal handler ids as an actual resource instead of an integer.

Storing it in an `Option` is exactly what you should do and it pushes you to a design that handles the signal handler ids as something that disappears when disconnecting.

I don't see how making it `Copy` improves anything here other than potentially making code working with signal handlers more fragile.

**Comment by mahkoh** [comment]
>Because if it overflows then GTK already killed the process via g_error() in the code you linked:

I wasn't sure if `G_DISABLE_CHECKS` is usually set or not in GTK builds.

>Storing it in an Option is exactly what you should do and it pushes you to a design that handles the signal handler ids as something that disappears when disconnecting.

Rust does not support this properly because it does not have destructuring drop, i.e., drop that can move out of the fields. If you are disconnecting outside of drops, then your approach makes sense to me.

Since you're providing an escape hatch via `as_raw` and `from_glib` this is not a serious issue so I'm fine with leaving it as is if you're not convinced.

**Comment by mahkoh** [comment]
I think your argument generalizes to the statement that hash maps should return a `Key` object upon insert and only allow removing elements by passing in this `Key` object (moving it.) At least I have not seen any argument why the signal handler hash map is different from any other hash maps in this regard.

I've not seen any general purpose hash map implementations that do this.

**Comment by GuillaumeGomez** [comment]
Well, in any case, it won't happen so closing this issue. If you found a bug using the Rust API, please open another issue with the problem.

**Comment by sdroege** [comment]
> I wasn't sure if `G_DISABLE_CHECKS` is usually set or not in GTK builds.

If you use a GLib build with checks disabled then you're basically on your own :) These checks are preventing bad behaviour in quite a few places, and you have to explictly disable them during the GLib build.
