### ISSUE TITLE
[BUG] failed to parse manifest

### ISSUE THREAD

**Issue by remcokranenburg** [gtk-rs/gtk-rs-core#472]
**Bug description**

Cannot build project with glib 0.15.0. Version 0.14.8 works.

**Error message**

```
error: failed to parse manifest at `/home/remco/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.0/Cargo.toml`

Caused by:
  can't find library `glib`, rename file to `src/lib.rs` or specify lib.path
```

**Comment by remcokranenburg** [comment]
Sorry, wrong project.

**Comment by remcokranenburg** [comment]
Oh wait, it is the right project! :man_facepalming:

**Comment by sdroege** [comment]
Happens because of https://github.com/gtk-rs/gtk-rs-core/blob/ed4be6260b00d79fa4afb282a1b907dcbafc39e7/glib/Cargo.toml#L15

It only includes that file then and nothing else, and not even that file because it's outside the current directory. Too bad `cargo publish` didn't catch that during the test build, very strange.

Thanks for reporting :)

**Comment by Subsentient** [comment]
Is it fixed yet? I have several dependencies that pull in glib-sys implicitly and it's a PITA to try and downgrade all of them manually.
I could really use a patch release quickly. :^(

**Comment by bilelmoussaoui** [comment]
Sorry for the inconvenience but not going to happen till tomorrow. Also those dependencies should ideally be fixed as well.

**Comment by sdroege** [comment]
> Is it fixed yet? I have several dependencies that pull in glib-sys implicitly and it's a PITA to try and downgrade all of them manually.
> I could really use a patch release quickly. :^(

OOC, how is this causing such problems for you? You have to manually update the dependency version in your `Cargo.toml` for the new version to be picked up.

**Comment by bilelmoussaoui** [comment]
Not if you have glib-sys as an indirect dependency that was set with version ="*"

**Comment by sdroege** [comment]
Ah right, but why would you no set a proper version?

**Comment by bilelmoussaoui** [comment]
No idea why would someone do that...

**Comment by remcokranenburg** [comment]
I discovered this bug while trying to publish my very first crate: https://github.com/remcokranenburg/gtk4-glium

So I'm not experienced in the least, but I *think* that we're encouraged to be flexible in your dependency versions, so your users can combine your crate with other crates (that have their own version requirements). I couldn't figure out how to specify a flexible minimum version and also blacklist a broken specific version, but it was late so I may have missed it.

**Comment by sdroege** [comment]
You would always put a specific version into the `Cargo.toml` that gives the API version of the dependency. So for `glib` you would now put `0.15` and that would make sure that any `0.15.x` version can be used with your crate. `0.14.x` and `0.16.x` won't automatically be used and that's correct because they will have a different API.

If there's not a zero at the beginning of the version number, you shift it all by one item. `1.0` would give you all `1.x` versions but not `2.x` or `0.x`.

Similarly `0.15.2` would mean `0.15.x with x >= 2`.

**Comment by sdroege** [comment]
That should also be documented somewhere in the cargo reference btw: https://doc.rust-lang.org/stable/cargo/reference/ . This is not specific to these crates here but generally for all cargo dependencies.

**Comment by remcokranenburg** [comment]
Ah, that makes sense. I come from a JS world, where it's common have support for several incompatible versions in one codebase, but that doesn't work the same way for Rust.

**Comment by sdroege** [comment]
You can also do that in Rust but you need to be careful that the versions are actually compatible enough for your crate. Something like `>= 0.14, < 0.16` will work.

**Comment by sdroege** [comment]
Nice crate btw, that looks useful :)

**Comment by sdroege** [comment]
0.15.0 / 0.4.0 is yanked from crates.io and new releases (0.15.1/0.4.1) coming soonish.

**Comment by sdroege** [comment]
New releases are up.
