### ISSUE TITLE
[FEATURE REQUEST] Add Variant::is_object_path()

### ISSUE THREAD

**Issue by lucab** [gtk-rs/gtk-rs-core#622]
It looks like [g_variant_is_object_path()](https://docs.rs/glib-sys/latest/glib_sys/fn.g_variant_is_object_path.html) does not currently have a safe wrapper in `glib`.

Among several possible approaches, there is consensus to expose it as `Variant::is_object_path(&str)->bool` so that it can be easily found.

**Comment by lucab** [comment]
These are the ones I've seen, aggregating similar ones by signatures (the crossed ones already have wrappers):
 1. string -> bool: `g_variant_is_object_path`, `g_variant_is_signature`
 2. Variant -> bool: `g_variant_is_floating`, `g_variant_is_normal_form`, ~~`g_variant_is_container`~~
 3. (Variant, Type) -> bool: ~~`g_variant_is_of_type`~~

I'll start tackling the first bucket, which is the one I cared about initially.

**Comment by sdroege** [comment]
> 2\. `g_variant_is_floating`

This will always return `false` for us :)

**Comment by jf2048** [comment]
Would it be wanted to have some types for `ObjectPath` and `ObjectPathBuf`? They could be similar to `VariantTy` and `VariantType`, i.e. do the checking during construction, and then could also implement `StaticVariantType` of `o`

And then some would also be needed for dbus signatures because those are a subset of GVariant types.

**Comment by lucab** [comment]
@slomo good point! Then I guess it doesn't make much sense to wrap that.

I added wrappers for all the other three methods in https://github.com/gtk-rs/gtk-rs-core/pull/632.
