### ISSUE TITLE
[BUG] Missing `ToValueOptional` on struct derived with `glib::Boxed` despite having `#[boxed_nullable]`

### ISSUE THREAD

**Issue by SeaDve** [gtk-rs/gtk-rs-core#652]
**Bug description**
```rust
#[derive(Clone, Debug, glib::Boxed)]
#[boxed_type(name = "SomeBoxedValue")]
#[boxed_nullable]
struct SomeBoxedValue();

Some(SomeBoxedValue()).to_value();  // ToValueOptional not satisfied
```

**Comment by sdroege** [comment]
This seems to work fine in the tests: https://github.com/gtk-rs/gtk-rs-core/blob/e28e523d66a5f8d79da4eb04490b25b6b1e8488c/glib-macros/tests/test.rs#L150-L181

I think the problem is

```diff
-#[boxed_type(name = "SomeBoxedValue")]
-#[boxed_nullable]
+#[boxed_type(name = "SomeBoxedValue", nullable)]
```

If that works, can you submit a PR that removes the `boxed_nullable` and `shared_boxed_nullable` attributes from `glib-macros/src/lib.rs`?

**Comment by SeaDve** [comment]
That works properly, after moving nullable to boxed_type.

> If that works, can you submit a PR that removes the boxed_nullable and shared_boxed_nullable attributes from glib-macros/src/lib.rs?

Sure, thanks!
