### ISSUE TITLE
ParamSpecBuilder functions named inconsistently

### ISSUE THREAD

**Issue by vivia** [gtk-rs/gtk-rs-core#750]
It's `.minimum()` and `.maximum()` but `.default_value()` and not `.min_value()`/`.max_value()` and also not `.default()`.

It's also `.read_only()` but `.readwrite()`, notice inconsistency in underscore usage.

cc @bilelmoussaoui

**Comment by bilelmoussaoui** [comment]
I suppose we can change `default_value` to `default` and `readwrite` to `read_write`. Would that be fine for you?

**Comment by vivia** [comment]
It would be fine for me in theory, but `default` collides with the inherited trait from the `Default` trait.

**Comment by bilelmoussaoui** [comment]
Ah indeed. What do you think @ranfdev @sdroege ?

**Comment by ranfdev** [comment]
`default_value` is also used outside of the builders. See `ParamSpecInt`. Unless we change it everywhere, we should keep it as it is.

`readwrite` comes from `ParamFlags::READWRITE`. Same logic applies here.

Maybe we could change `read_only` to `only_readable` so that it resembles to `ParamFlags::READABLE`?

**Comment by sdroege** [comment]
I think it would be nice to make it more consistent. Names between the builder and the getter should of course stay the same in any case.

The reason why I called it `default_value` was that a) `default` is covered by the `Default` trait already, b) in C it's also `minimum`/`maximum`/`default_value` because `default` is a keyword in C. We could append `_value` to the min/max if people prefer that.

`read_write()` instead of `readwrite()` seems fine to me, `read_only()` sounds better than `only_readable()`.

**Comment by sdroege** [comment]
As there are no good suggestions, let's close this then :)
