### ISSUE TITLE
glib_build_tools crate on crates.io has broken link

### ISSUE THREAD

**Issue by pbor** [gtk-rs/gtk-rs-core#833]
The documentation links give 404

**Comment by sdroege** [comment]
https://github.com/gtk-rs/gtk-rs-core/blob/master/.github/workflows/docs.yml#L40 seems to do the right thing already to build the docs.

It's also available from https://gtk-rs.org/gtk-rs-core/git/docs/glib_build_tools/index.html

So it seems the problem is only the underscores vs. dashes? Do you want to submit a PR @pbor ?

**Comment by pbor** [comment]
I am not quite sure what needs to be patched... the workflow file itself?

**Comment by sdroege** [comment]
The Cargo.toml
