### ISSUE TITLE
[BUG] Gdk.PixbufAnimation.iter() gets a Duration but should be Option<Duration> as the argument is nullable

### ISSUE THREAD

**Issue by aruiz** [gtk-rs/gtk-rs-core#918]
When trying to subclass Gdk.PixbufAnimation I have noticed that the iter(&self, start_time: Duration) method should accept an Option<Duration> to map well to the original API.

When NULL, it calls g_get_current_time() internally so it is not a big deal if we don't change it but I thought I'd bring it up.

**Comment by sdroege** [comment]
https://github.com/gtk-rs/gtk-rs-core/blob/master/gdk-pixbuf/src/pixbuf_animation.rs#L16 it gets an `Option<SystemTime>` though. Are you talking about some other API?

**Comment by sdroege** [comment]
The subclass version takes a `Duration` because, as you say, the C library will always fill it in with a value if the caller passes `NULL`.

https://github.com/gtk-rs/gtk-rs-core/blob/master/gdk-pixbuf/src/subclass/pixbuf_animation.rs#L25

Not sure why one is a `SystemTime` and one ` Duration` though. That seems strange.

**Comment by jf2048** [comment]
We had a discussion about this class in Matrix recently, it probably should not be subclassed or even used at all unless you need backwards compatibility with some C code or something. The use of `GTimeVal` is obsolete and there is no replacement API. You may consider using `gtk::MediaFile` or using one of the other image loading crates to handle animated gifs instead.

**Comment by bilelmoussaoui** [comment]
> We had a discussion about this class in Matrix recently, it probably should not be subclassed or even used at all unless you need backwards compatibility with some C code or something. The use of `GTimeVal` is obsolete and there is no replacement API. You may consider using `gtk::MediaFile` or using one of the other image loading crates to handle animated gifs instead.

That's not the use case here, it is for porting the webp-pixbuf-loader to Rust.

**Comment by jf2048** [comment]
Oh then ignore me, that would fall under backwards compatibility with some C code :)

**Comment by sdroege** [comment]
What exactly should happen here now?

**Comment by aruiz** [comment]
My take is that we should allow Option<Duration>, otherwise we need to do SystemTime::now().ellapsed(SystemTime::UNIX_EPOCH) every time we call this function. Most of the time you just want now so that seems awfully verbose for every user of the API.

**Comment by sdroege** [comment]
On the [`Ext`](https://gtk-rs.org/gtk-rs-core/git/docs/gdk_pixbuf/prelude/trait.PixbufAnimationExtManual.html#tymethod.iter) trait it already takes an `Option`, which makes sense because of how the C function is implemented. The C code currently does

```cpp
GdkPixbufAnimationIter*
gdk_pixbuf_animation_get_iter (GdkPixbufAnimation *animation,
                               const GTimeVal     *start_time)
{
        GTimeVal val;

        g_return_val_if_fail (GDK_IS_PIXBUF_ANIMATION (animation), NULL);


        if (start_time)
                val = *start_time;
        else
                g_get_current_time (&val);

        return GDK_PIXBUF_ANIMATION_GET_CLASS (animation)->get_iter (animation, &val);
}
```

That OTOH also means that there is no way the function on the `Impl` trait could be called with `None`. Which means that [this](https://gtk-rs.org/gtk-rs-core/git/docs/gdk_pixbuf/subclass/pixbuf_animation/trait.PixbufAnimationImpl.html#method.iter) seems correct too.

What exactly do you suggest to change?

----

The only thing I don't understand is why one takes a `Duration` and the other a `SystemTime`. AFAICS both should take a `SystemTime`.

**Comment by aruiz** [comment]
I think this is the change we ought to make:
```PixbufAnimationImpl::iter(&self, start_time: Option<SystemTime>)```

We allow None and we use SystemTime which maps better with the original API (store a clock timestamp rather than a generic timespan).

**Comment by sdroege** [comment]
> I think this is the change we ought to make: `PixbufAnimationImpl::iter(&self, start_time: Option<SystemTime>)`

How would you ever end up with a `None` here though? The C library is never going to call this function with `NULL`.

> use SystemTime which maps better with the original API (store a clock timestamp rather than a generic timespan).

I agree

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk-rs-core/pull/933 for the fixes of the type confusion. I'm still not sure where/why you want to have something changed to an `Option` though.
