### ISSUE TITLE
properties: support for ParamSpecOverride

### ISSUE THREAD

**Issue by ranfdev** [gtk-rs/gtk-rs-core#946]
There's no type with a `HasParamSpec::ParamSpec` of value `ParamSpecOverride`, so there's currently no way to define that kind of properties.

Probably we should add two attributes, `override_interface` and `override_class`.
Example
```
#[property(get, set, override_interface = gtk::Actionable]
pub action_name: RefCell<Option<glib::GString>>
```

That means we are polluting the attribute namespace with `override_interface` and `override_class`, but I guess these two won't be used as methods for any `ParamSpecXBuilder` anyway.

**Comment by sdroege** [comment]
Sounds like a good plan to me

**Comment by pbor** [comment]
I tried to start this one here: https://github.com/gtk-rs/gtk-rs-core/compare/master...pbor:gtk-rs-core:prop-override

The override itself seems to work, but I do not get why instead `let not_overridden: u32 = myfoo.property("not-overridden");` tells me that the property is not there...

Also, it is not very clear to me if we need to use `ParamSpecOverride::for_class/interface` like I did, or if we can use `ParamSpecOverrideBuilder` and feed it the param spec instead of the name... if that was possible then maybe the syntax could just be `override(gtk::Actionable)` and we would not even pollute the namespace of the builder

**Comment by ranfdev** [comment]
I think you are missing

```rust
fn constructed(&self) {
    self.parent_constructed();
}
```

In the ObjectImpl

**Comment by ranfdev** [comment]
> if we can use ParamSpecOverrideBuilder and feed it the param spec instead of the name

That needs a way to override the `ParamSpecXBuilder` used. Then the user also needs to retrieve the correct ParamSpec to override... 

The result will look like

```
#[property(get, set, builder = builder_override_interface::<gtk::Actionable>(), overridden = get_param_spec::<gtk::Actionable>("action-name")]
action_name: RefCell<String>
```

It's too long and requires the user to specify the property name again.
