### ISSUE TITLE
[FEATURE REQUEST] #[glib::object_impl] attribute macro

### ISSUE THREAD

**Issue by BrainBlasted** [gtk-rs/gtk-rs-core#982]
This would be a macro that handles filling in the `glib::subclass:ObjectImpl` methods. Particularly those for properties and signals. An example of a case we want to be able to generate:

```rust
impl ObjectImpl for Foo {
    fn properties() -> &'static [ParamSpec] {
        Self::derived_properties()
    }
    fn set_property(
        &self,
        _id: usize,
        _value: &Value,
        _pspec: &ParamSpec,
    ) {
        Self::derived_set_property(self, _id, _value, _pspec)
    }
    fn property(&self, _id: usize, _pspec: &ParamSpec) -> Value {
        Self::derived_property(self, _id, _pspec)
    }
}
```

Ideally could be condensed to something like:

```rust
#[glib::object_impl]
impl ObjectImpl for Foo {}
```

**Comment by sdroege** [comment]
This would have to be at least `#[glib::object_impl(derived_properties)]` or so, otherwise we can't extend it later with something for signals for example.

I don't think whether to expand to that or not is auto-detectable as there are 3 different cases:
  - no properties and none of those functions are defined (and the macro should not add them)
  - properties and those functions are not defined (and the macro should add them)
  - properties and (some of?) those functions are defined (and the macro should not add them)

The first two cases can't be distinguished.

**Comment by sdroege** [comment]
CC @ranfdev

**Comment by ranfdev** [comment]
I would keep things explicit with `#[glib::object_impl(derived_properties)]`

**Comment by jf2048** [comment]
Added a simple implementation of this as a derive macro into my PR here: https://github.com/gtk-rs/gtk-rs-core/pull/970/commits/287aebfbdfa88cfd0b172856af3fd50b01d069f5

**Comment by bilelmoussaoui** [comment]
This is now solved with `glib::derived_properties`
